CATEGORY_PATH = "data/categories/"
TERM_CATEGORIES = ['industry', 'innovation']
OTHER_CATEGORIES = ['arts', 'life']
STOP_WORDS_COUNTER = 100
TERMS_COUNTER = 20
STOP_WORDS_THRESHOLD = 0.0002
TERMS_THRESHOLD = 0.0002
CONTRAST_THRESHOLD = 1e-04